### ISSUE TITLE
Mac版本的Notion按照作者的方法无法更改为简体中文

### ISSUE THREAD

**Issue by qianye216** [Reamd7/notion-zh_CN#1]
Mac桌面端notion下载notion-zh_CN.js文件到renderer目录，然后在preload.js中加入最后一行代码无法生效
打开显示的是英文

**Comment by yongbingwang** [comment]
> Mac桌面端notion下载notion-zh_CN.js文件到renderer目录，然后在preload.js中加入最后一行代码无法生效
> 打开显示的是英文

我看他写的是更改为韩文，在Mac下的那个目录结构可以发下吗，没有找到，谢谢

**Comment by qianye216** [comment]
> > Mac桌面端notion下载notion-zh_CN.js文件到renderer目录，然后在preload.js中加入最后一行代码无法生效
> > 打开显示的是英文
> 
> 我看他写的是更改为韩文，在Mac下的那个目录结构可以发下吗，没有找到，谢谢

/Applications/Notion.app/Contents/Resources/app/renderer/preload.js  是这个路径吗

**Comment by yongbingwang** [comment]
> > > Mac桌面端notion下载notion-zh_CN.js文件到renderer目录，然后在preload.js中加入最后一行代码无法生效
> > > 打开显示的是英文
> > 
> > 
> > 我看他写的是更改为韩文，在Mac下的那个目录结构可以发下吗，没有找到，谢谢
> 
> /Applications/Notion.app/Contents/Resources/app/renderer/preload.js 是这个路径吗

没有找到这个路径，你是更改的哪个路径下的文件

**Comment by qianye216** [comment]
> > > > Mac桌面端notion下载notion-zh_CN.js文件到renderer目录，然后在preload.js中加入最后一行代码无法生效
> > > > 打开显示的是英文
> > > 
> > > 
> > > 我看他写的是更改为韩文，在Mac下的那个目录结构可以发下吗，没有找到，谢谢
> > 
> > 
> > /Applications/Notion.app/Contents/Resources/app/renderer/preload.js 是这个路径吗
> 
> 没有找到这个路径，你是更改的哪个路径下的文件

就是更改的这个路径的preload.js文件
![image](https://user-images.githubusercontent.com/8281775/129538357-2ebfd529-2a47-4df1-9417-5b5242a7a644.png)

**Comment by Reamd7** [comment]
> > Mac桌面端notion下载notion-zh_CN.js文件到renderer目录，然后在preload.js中加入最后一行代码无法生效
> > 打开显示的是英文
> 
> 我看他写的是更改为韩文，在Mac下的那个目录结构可以发下吗，没有找到，谢谢

在应用程序文件夹中，右键notion，显示应用包结构

**Comment by yongbingwang** [comment]
> > > Mac桌面端notion下载notion-zh_CN.js文件到renderer目录，然后在preload.js中加入最后一行代码无法生效
> > > 打开显示的是英文
> > 
> > 
> > 我看他写的是更改为韩文，在Mac下的那个目录结构可以发下吗，没有找到，谢谢
> 
> 在应用程序文件夹中，右键notion，显示应用包结构

找到了，修改为韩文之后操作，还是英文界面

**Comment by qianye216** [comment]
> > > Mac桌面端notion下载notion-zh_CN.js文件到renderer目录，然后在preload.js中加入最后一行代码无法生效
> > > 打开显示的是英文
> > 
> > 
> > 我看他写的是更改为韩文，在Mac下的那个目录结构可以发下吗，没有找到，谢谢
> 
> 在应用程序文件夹中，右键notion，显示应用包结构

![image](https://user-images.githubusercontent.com/8281775/129541998-59b5aa18-4d02-44da-8715-a75ae2c52b7c.png)
[目录树.txt](https://github.com/Reamd7/notion-zh_CN/files/6991209/default.txt)

**Comment by Reamd7** [comment]
> Mac桌面端notion下载notion-zh_CN.js文件到renderer目录，然后在preload.js中加入最后一行代码无法生效
> 打开显示的是英文

已经更新了修复了mac中无效的问题

**Comment by qianye216** [comment]
> > Mac桌面端notion下载notion-zh_CN.js文件到renderer目录，然后在preload.js中加入最后一行代码无法生效
> > 打开显示的是英文
> 
> 已经更新了修复了mac中无效的问题

验证已正常，谢谢作者😆

**Comment by yongbingwang** [comment]
> > > Mac桌面端notion下载notion-zh_CN.js文件到renderer目录，然后在preload.js中加入最后一行代码无法生效
> > > 打开显示的是英文
> > 
> > 
> > 已经更新了修复了mac中无效的问题
> 
> 验证已正常，谢谢作者😆

ok了，非常感谢
