### ISSUE TITLE
确认过，mac，web用这个都是好的😀

### ISSUE THREAD

**Issue by jyking** [Reamd7/notion-zh_CN#100]
> mac端无法打开、app白页

不好意思，我这边没有mac环境，无法进行测试，只能看有没有别的贡献者来排查了。

BTW，想问下您那边网页端可以使用吗

_Originally posted by @shiquda in https://github.com/Reamd7/notion-zh_CN/issues/97#issuecomment-1695408711_

**Comment by shiquda** [comment]
感谢反馈❤️
