### ISSUE TITLE
‼️紧急求助，汉化不生效

### ISSUE THREAD

**Issue by LioneLVV** [Reamd7/notion-zh_CN#102]
mac m2芯片版本无法汉化，之前可用！notion版本2.1.23 求助

**Comment by Tim-Saijun** [comment]
把js文件换成这里的就好了https://github.com/Reamd7/notion-zh_CN/blob/107c35a9e35d316af681d7ad7d7a9b82e8e92a38/notion-zh_CN.js

**Comment by guojiang43** [comment]
> 把js文件换成这里的就好了https://github.com/Reamd7/notion-zh_CN/blob/107c35a9e35d316af681d7ad7d7a9b82e8e92a38/notion-zh_CN.js

亲测有效，intel macbook pro

**Comment by BLACKFTVV** [comment]
> mac m2芯片版本无法汉化，之前可用！notion版本2.1.23 求助

M1版本的notion也不行了

**Comment by ku-z** [comment]
@guojiang43 感谢！

**Comment by kyc20010501** [comment]
> https://github.com/Reamd7/notion-zh_CN/blob/107c35a9e35d316af681d7ad7d7a9b82e8e92a38/notion-zh_CN.js

替换之后还是不行诶，之前是可用的

**Comment by bobo0810** [comment]
> 把js文件换成这里的就好了https://github.com/Reamd7/notion-zh_CN/blob/107c35a9e35d316af681d7ad7d7a9b82e8e92a38/notion-zh_CN.js

M1 mac亲测可用

**Comment by baobaotql** [comment]
二楼方法有效  m1亲测

**Comment by shcw** [comment]
亲测2楼m1 mac有效

**Comment by githubcatheaven** [comment]
m2 mac worked.

**Comment by natuaki** [comment]
m1 可以用

**Comment by yaotong1985** [comment]
https://github.com/shiquda/notion-zh_CN/blob/main/notion-zh_CN.js
这个亲测M1可行

**Comment by Reamd7** [comment]
已修复
