### ISSUE TITLE
汉化失败

### ISSUE THREAD

**Issue by keke1998** [Reamd7/notion-zh_CN#105]
因特尔版Mac mini 汉化失败 是因为最近notion的更新么 按照楼下的方案 更换js文件后   切换语言还是没用   求大神

**Comment by HyperHyToo** [comment]
同样问题，我的汉化本来好好的，突然就不行了，重新试了好几遍都是这样，就大神解答

**Comment by xixiwd** [comment]
我也是，在更新一次后，之前的汉化方式就失效了

**Comment by xixiwd** [comment]
把js文件换成这里的就好了https://github.com/Reamd7/notion-zh_CN/blob/107c35a9e35d316af681d7ad7d7a9b82e8e92a38/notion-zh_CN.js
————转自隔壁

**Comment by Reamd7** [comment]
已修复
