### ISSUE TITLE
macos 上已经更新自动工具进行处理，问题收集， Mac 2.2.0 文件目录结构发生了变化

### ISSUE THREAD

**Issue by LeonShannon** [Reamd7/notion-zh_CN#111]
<img width="920" alt="image" src="https://github.com/Reamd7/notion-zh_CN/assets/24221796/e32c6e0f-e2d5-4274-9913-d0121b076f6d">
<img width="284" alt="image" src="https://github.com/Reamd7/notion-zh_CN/assets/24221796/5f99a2cb-5a5f-4a5e-a0b9-9cb6c69b9b6d">

**Comment by Reamd7** [comment]
收到，我也刚发现，让我看看如何处理比较容易上手

**Comment by each1026** [comment]
确实

**Comment by SayNo233** [comment]
所以现在MAC版最新汉化，还需要等大佬给方案。以及之前会经常出现回滚操作，汉化完了，后续打开重新归零了是为什么？

**Comment by sunianpan** [comment]
等待⌛️大佬给方案

**Comment by onenora** [comment]
解包/Applications/Notion.app/Contents/Resources/app.asar，还是看不懂这个目录的汉化脚本应该放在哪
<img width="600" alt="image" src="https://github.com/Reamd7/notion-zh_CN/assets/99520915/a005e901-a5e8-41c0-bed0-fd93b9b0613b">

**Comment by beifeng777** [comment]
等待大佬

**Comment by Reamd7** [comment]
> 解包/Applications/Notion.app/Contents/Resources/app.asar，还是看不懂这个目录的汉化脚本应该放在哪 <img alt="image" width="600" src="https://user-images.githubusercontent.com/99520915/268270126-a005e901-a5e8-41c0-bed0-fd93b9b0613b.png">

解完就是放renderer目录下。
依旧还是插入 preload.js。

**Comment by Reamd7** [comment]
> 所以现在MAC版最新汉化，还需要等大佬给方案。以及之前会经常出现回滚操作，汉化完了，后续打开重新归零了是为什么？

这是因为官方更新程序更新完所有文件都删了只剩下官方文件了。所以都是要重新汉化的，只是现在改了方案手动改文件就很麻烦了，要写一个程序。。

**Comment by Reamd7** [comment]
省流：动手能力强的百度asar文件解包，解压缩之后将原有asar文件备份（重命名），然后解压出来的app.asar文件夹里面还是有renderer，步骤如旧

**Comment by smile-wan** [comment]
通过解包app.asar后发现文件结构和之前的好像还是不一样，在众多文件夹中检索到了renderer之后里面内容还是不太一样。
![iShot_2023-09-16_00 32 41](https://github.com/Reamd7/notion-zh_CN/assets/144999700/ec1e30f5-bfed-427e-8ec1-8c479b76e969)
![image](https://github.com/Reamd7/notion-zh_CN/assets/144999700/00d68cdb-6b1e-478a-9de2-3e3081c47541)

**Comment by onenora** [comment]
> > 解包/Applications/Notion.app/Contents/Resources/app.asar，还是看不懂这个目录的汉化脚本应该放在哪 <img alt="image" width="600" src="https://user-images.githubusercontent.com/99520915/268270126-a005e901-a5e8-41c0-bed0-fd93b9b0613b.png">
> 
> 解完就是放renderer目录下。 依旧还是插入 preload.js。
# OK了，谢谢~
<img width="700" alt="image" src="https://github.com/Reamd7/notion-zh_CN/assets/99520915/2932880d-61ea-40d0-8862-83b766632bd4">

**Comment by jim3997516** [comment]
> > > 解包/Applications/Notion.app/Contents/Resources/app.asar，还是看不懂这个目录的汉化脚本应该放在哪 <img alt="image" width="600" src="https://user-images.githubusercontent.com/99520915/268270126-a005e901-a5e8-41c0-bed0-fd93b9b0613b.png">
> > 
> > 
> > 解完就是放renderer目录下。 依旧还是插入 preload.js。
> 
> # OK了，谢谢~
> <img alt="image" width="700" src="https://user-images.githubusercontent.com/99520915/268347057-2932880d-61ea-40d0-8862-83b766632bd4.png">

这是哪个软件弄的？

**Comment by 11pmsleep** [comment]
> 省流：动手能力强的百度asar文件解包，解压缩之后将原有asar文件备份（重命名），然后解压出来的app.asar文件夹里面还是有renderer，步骤如旧

解完包之后，没有renderer这个文件夹
![image](https://github.com/Reamd7/notion-zh_CN/assets/72010343/bd5f8ae3-881e-47de-9451-ae5372c8df90)

**Comment by justinzm** [comment]
我解压后也是没有renderer这个文件夹？

**Comment by catoamao** [comment]
https://www.bilibili.com/read/cv26564916/?from=search  这里有个教程可以了

**Comment by jim3997516** [comment]
> https://www.bilibili.com/read/cv26564916/?from=search 这里有个教程可以了

谢谢！ 试验了一下成功了

**Comment by HarveyXWu** [comment]
> > https://www.bilibili.com/read/cv26564916/?from=search 这里有个教程可以了
> 
> 谢谢！ 试验了一下成功了

请教一下，我使用这个后notion一直转圈打不开，有老哥遇到过这个情况吗？谢谢！

**Comment by Reamd7** [comment]
macos 上已经更新自动工具进行处理，看看各位还遇到什么问题这里进行问题收集

[https://github.com/Reamd7/notion-zh_CN#mac](教程)
