### ISSUE TITLE
Windows客户端汉化失败

### ISSUE THREAD

**Issue by PlantJH0** [Reamd7/notion-zh_CN#113]
更新完后无法汉化了

**Comment by Glimmer09** [comment]
用VSCode下个VSCode Archive扩展解包app.asar，然后和以前一样用PowerShell装汉化，再打包回去，替换原本的，就好了

**Comment by zsgcgrs** [comment]
[windows版app.asar.zip](https://github.com/Reamd7/notion-zh_CN/files/12640574/windows.app.asar.zip)
做了一个win版汉化，实测ok，直接替换即可

**Comment by Dear-XiaoBai** [comment]
> [windows版app.asar.zip](https://github.com/Reamd7/notion-zh_CN/files/12640574/windows.app.asar.zip) 做了一个win版汉化，实测ok，直接替换即可

替换成功，中文又回来了，谢谢

**Comment by dongzi2023** [comment]
能不能做一个 Mac版的app.asar.zip的啊，多谢啦，十分期待

**Comment by moliango** [comment]
> 能不能做一个Mac版的app.asar.zip的啊，多谢啦，十分期待
试试这个
[app.asar.zip](https://github.com/Reamd7/notion-zh_CN/files/12646451/app.asar.zip)

**Comment by dongzi2023** [comment]
> > 能不能做一个Mac版的app.asar.zip的啊，多谢啦，十分期待
> > 尝试一下这个
> > [app.asar.zip](https://github.com/Reamd7/notion-zh_CN/files/12646451/app.asar.zip)

十分感谢

**Comment by zsgcgrs** [comment]
> https://github.com/Reamd7/notion-zh_CN#windows 各位尝试一下这个方案，希望有大家的反馈

测试正常
