### ISSUE TITLE
windows中无法注入自动汉化

### ISSUE THREAD

**Issue by Chengxcy** [Reamd7/notion-zh_CN#115]
使用的notion版本：Notion Setup 2.2.0.exe
按照教程操作：手动注入：

windows
下载 [release](https://github.com/Reamd7/notion-zh_CN/releases/tag/2.4.20-win-asar) ，更新 env.toml 中 folder 字段为自己 notion 安装目录，运行 update_asar.exe。
汉化不了啊，还有其他要注意的方面吗？
以前的添加的方法也不行了，都找不到相应的renderer文件夹了。

**Comment by Chengxcy** [comment]
参照这个教程，替换，汉化成功，可以使用。https://www.bilibili.com/read/cv26564916/?from=search

**Comment by Reamd7** [comment]
这个教程每次都要替换意义就不大了。我想问你安装完notion之后，点击这个自动汉化的工具，notion之后的文件目录是怎么样的

**Comment by Reamd7** [comment]
希望收集相关信息以完善这个工具

**Comment by StephenBDR** [comment]
> 这个教程每次都要替换意义就不大了。我想问你安装完notion之后，点击这个自动汉化的工具，notion之后的文件目录是怎么样的

我是运行update_asar.exe，闪了一下就没了，不知道啥原因(┬＿┬)，大佬求救

**Comment by altzh666** [comment]
> > 这个教程每次都要替换意义就不大了。我想问你安装完notion之后，点击这个自动汉化的工具，notion之后的文件目录是怎么样的
> 
> 我是运行update_asar.exe，闪了一下就没了，不知道啥原因(┬＿┬)，大佬求救

+1 先是改了env.toml 中 folder 字段，然后运行update_asar.exe就闪退

**Comment by Chengxcy** [comment]
> > 这个教程每次都要替换意义就不大了。我想问你安装完notion之后，点击这个自动汉化的工具，notion之后的文件目录是怎么样的
> 
> 我是运行update_asar.exe，闪了一下就没了，不知道啥原因(┬＿┬)，大佬求救

我也是闪一下就没了，用的系统是win11

**Comment by Chengxcy** [comment]
> 这个教程每次都要替换意义就不大了。我想问你安装完notion之后，点击这个自动汉化的工具，notion之后的文件目录是怎么样的

点这个汉化工具后，软件工具就闪一下，目录没有任何变化，notion里的文件也没有变动。用的系统是win11。有需要测试的地方我愿意配合测试完善工具

**Comment by JacKooDesu** [comment]
#116 的PR，Build ↓
[Notion Han.zip](https://github.com/Reamd7/notion-zh_CN/files/12683451/Notion.Han.zip)

**Comment by Reamd7** [comment]
出现闪退的同学 看看自己的 folder 是不是用 `\` 分割
@Chengxcy @altzh666 @StephenBDR

!! 注意 window 下路径一定不能用 `\` 分割 ，要用 `/`.
!! 例如:
```
# 这是 env.toml 内容，folder 不能为 C:\Users\用户名\AppData\Local\Programs\Notion，必须为 C:/Users/用户名/AppData/Local/Programs/Notion
version = "2.4.21"
folder = "C:/Users/用户名/AppData/Local/Programs/Notion"
remote_url="https://greasyfork.org/scripts/430116-notion-zh-cn-notion%E7%9A%84%E6%B1%89%E5%8C%96%E8%84%9A%E6%9C%AC/code/Notion-zh_CN%20notion%E7%9A%84%E6%B1%89%E5%8C%96%E8%84%9A%E6%9C%AC.user.js"

**Comment by Chengxcy** [comment]
> 出现闪退的同学 看看自己的 folder 是不是用 `\` 分割 @Chengxcy @altzh666 @StephenBDR
> 
> !! 注意 window 下路径一定不能用 `\` 分割 ，要用 `/`. !! 例如:
> 
> ```
> # 这是 env.toml 内容，folder 不能为 C:\Users\用户名\AppData\Local\Programs\Notion，必须为 C:/Users/用户名/AppData/Local/Programs/Notion
> version = "2.4.21"
> folder = "C:/Users/用户名/AppData/Local/Programs/Notion"
> remote_url="https://greasyfork.org/scripts/430116-notion-zh-cn-notion%E7%9A%84%E6%B1%89%E5%8C%96%E8%84%9A%E6%9C%AC/code/Notion-zh_CN%20notion%E7%9A%84%E6%B1%89%E5%8C%96%E8%84%9A%E6%9C%AC.user.js"
> ```

感谢指导，这样可以了，原来目录路径分隔错了。[release](https://github.com/Reamd7/notion-zh_CN/releases/tag/2.4.20-win-asar)里面的备注错了，您上面的回复是对的。#注意 window 下路径一定不能用 `\` 分割 ，要用 `/`
![image](https://github.com/Reamd7/notion-zh_CN/assets/91258009/3cc35406-523e-492b-bbff-f9005d2e87a3)
