### ISSUE TITLE
window 上已经更新自动工具进行处理，问题收集， window 2.2.0 文件目录结构发生了变化

### ISSUE THREAD

**Issue by Reamd7** [Reamd7/notion-zh_CN#117]
相关教程：[https://github.com/Reamd7/notion-zh_CN#windows](url)

**Comment by Thetuo** [comment]
windows自动挡失败，文件路径用的也是/不是\

**Comment by shingo110** [comment]
还是没整明白那个update_asar.exe要咋用😂

**Comment by HaoqinChen** [comment]
> 还是没整明白那个update_asar.exe要咋用😂 按照说明下载修改配置文件，然后执行程序，闪一下就没了，没有汉化成功 ![image](https://user-images.githubusercontent.com/34878648/270550324-99bdaef3-7a0a-4cf5-8f77-354652154068.png)

一样，不知道咋搞

**Comment by ShangYi7** [comment]
一樣失敗

**Comment by itchaox** [comment]
@Reamd7 你好，路径用的 /，也是闪退了

**Comment by Reamd7** [comment]
https://github.com/Reamd7/notion-zh_CN/releases/tag/3.0.0
