### ISSUE TITLE
notion的windows客户端汉化又出幺蛾子了。

### ISSUE THREAD

**Issue by AShanWang** [Reamd7/notion-zh_CN#121]
大佬好！
现在2023年10月6日23:45:26，
发现notion的win客户端无法汉化，网页端正常
之前替换app.asar文件可以正常汉化，
今个上午用的时候都还都很正常。
然后呢，有过刚才有过一次自动更新，变回英文版后
正当我再次替换文件汉化时，发现无效，又是自动更新。依次循环。

**Comment by AShanWang** [comment]
已解决，
需要先删除.xml文件，
然后再替换app.asar文件，即可成功汉化。

**Comment by Reamd7** [comment]
https://github.com/Reamd7/notion-zh_CN/releases/tag/3.0.0
