### ISSUE TITLE
m2 无法运行汉化文件

### ISSUE THREAD

**Issue by githubcatheaven** [Reamd7/notion-zh_CN#122]
修改扩展名为.app运行报错，没有详细教程，怎么汉化？

**Comment by githubcatheaven** [comment]
sudo chmod +x update_asar_m1_mac 改成可执行文件了。
但是汉化后无效，切换韩文切回英文也无效

**Comment by chunge16** [comment]
update_asar_m1_mac 怎么执行这个文件呢？

**Comment by Reamd7** [comment]
https://github.com/Reamd7/notion-zh_CN/releases/tag/3.0.0
