### ISSUE TITLE
notion 2.2.1 汉化方法推荐，win，mac通用

### ISSUE THREAD

**Issue by Chunhui0536** [Reamd7/notion-zh_CN#123]
推荐b站UP的解决方案，
链接：【Notion中文汉化教程2.2.1版本10月最新支持Mac和Windows】 https://www.bilibili.com/video/BV1qz4y1G7j9/?share_source=copy_web&vd_source=66b1e71bd84f35104a59ca49412a1494

M1 ，系统14.0,遇到问题是打开转圈圈，可以通过网页跳转。
我使用Safari浏览器建了一个网页app，链接是一个空白页面，设置链接使用app打开，相当于一个启动程序。

**Comment by kpt1979** [comment]
用上啦。是真的可以。

**Comment by xiaoyifan0406** [comment]
真的可以+1

**Comment by qaz5391450** [comment]
真的可以+1

**Comment by qaz5391450** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
