### ISSUE TITLE
Notion 2.2.4 (Mac)汉化失败，文件夹内容异常

### ISSUE THREAD

**Issue by smile-wan** [Reamd7/notion-zh_CN#127]
解析.asar格式文件夹后，内容和之前不一致，汉化失败
<img width="284" alt="image" src="https://github.com/Reamd7/notion-zh_CN/assets/144999700/58dd6be3-3613-4af5-bb77-dbb6fe0fa7ca">

**Comment by smile-wan** [comment]
> 解析.asar格式文件夹后，内容和之前不一致，汉化失败 <img alt="image" width="284" src="https://user-images.githubusercontent.com/144999700/277656747-58dd6be3-3613-4af5-bb77-dbb6fe0fa7ca.png">

目前解决方法是用我之前打包的2.2.1版本的.asar文件进行替换，然后汉化生效

**Comment by yunzhongci** [comment]
跟之前的文件夹内容不一样了，按照原来的方式汉化已经失效

**Comment by owo10086** [comment]
https://www.123pan.com/s/DWS1jv-ou8WH.html
2.20-2.2.4直接替换包（我在b站找的）

**Comment by smile-wan** [comment]
> https://www.123pan.com/s/DWS1jv-ou8WH.html 2.20-2.2.4直接替换包（我在b站找的）

你有尝试过生效了嘛？

**Comment by owo10086** [comment]
> > https://www.123pan.com/s/DWS1jv-ou8WH.html 2.20-2.2.4直接替换包（我在b站找的）
> 
> 你有尝试过生效了嘛？

生效 目前正在用

**Comment by smile-wan** [comment]
> > > https://www.123pan.com/s/DWS1jv-ou8WH.html 2.20-2.2.4直接替换包（我在b站找的）
> > 
> > 
> > 你有尝试过生效了嘛？
> 
> 生效 目前正在用

我的上午转圈圈，我换成我自己之前打包的2.2.1版本的.asar文件就好了

**Comment by happykkAi** [comment]
替换后  一直转圈圈 ，我放弃汉化了

**Comment by graderhei** [comment]
> 替换后一直转圈圈，我放弃汉化了

打开梯子就行了，网络不太好
