### ISSUE TITLE
win2.2.4版本，app.asar文件里面已经没有preload.js了，求最新解决办法。但是在文件的i18n文件夹下，发现一个“zh_CN”文件夹，exe设置选项里找不到。

### ISSUE THREAD

**Issue by iris-aye** [Reamd7/notion-zh_CN#128]
![20231025 165657](https://github.com/Reamd7/notion-zh_CN/assets/68792019/448eb437-0b08-4a9f-8f12-927988811f85)

![20231025 165712](https://github.com/Reamd7/notion-zh_CN/assets/68792019/56f266e5-7524-4a7f-9f41-e7fd0de401e8)

**Comment by smile-wan** [comment]
跟mac问题一样，等修复吧

**Comment by aaazz47** [comment]
原来我还不是第一波被更新的呀，CMD运行了一下自动程序提示这么个错误，不过我假程序员啥也看不懂
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', update_asar/src/main.rs:82:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
![微信截图_20231026170259](https://github.com/Reamd7/notion-zh_CN/assets/19562000/5a801f17-bbac-4db3-a74e-9412c4eb1b3e)

**Comment by Barry04** [comment]
+1

**Comment by lazy3801** [comment]
蹲

**Comment by jyooo-x** [comment]
+1

**Comment by sytt3** [comment]
插眼，如果有方案，麻烦戳下我，谢谢

**Comment by jankos-night** [comment]
我用手动更新的app.asar直接替换注入后的文件夹就好了

**Comment by graderhei** [comment]
> 我用手动更新的app.asar直接替换注入后的文件夹就好了

有效

**Comment by fank243** [comment]
+1

**Comment by Reamd7** [comment]
https://github.com/Reamd7/notion-zh_CN/releases/tag/3.0.0
