### ISSUE TITLE
有人3.0.0汉化成功的嘛？求助（MAC 3.0.0版本）

### ISSUE THREAD

**Issue by smile-wan** [Reamd7/notion-zh_CN#135]
按照昨天大佬发的最新的3.0.0的教程，结果找不到这个文件夹
<img width="862" alt="image" src="https://github.com/Reamd7/notion-zh_CN/assets/144999700/28832442-13d9-49af-af34-28b9a1ef6b88">
也找不到对应的`index.js`，在其他的`index.js`文件里面搜索也没找到`localeHtml[r]`

**Comment by limochao** [comment]
我也没有找到，具体怎么操作呢

**Comment by limochao** [comment]
> > app文件夹可以找到吗
> 
> 这个得自己新建一个

具体怎么操作呢

**Comment by smile-wan** [comment]
> Windows半分钟搞定

可以分享一下流程嘛？

**Comment by louiejordan** [comment]
> > Windows半分钟搞定
> 
> 可以分享一下流程嘛？

就按照说明里的方法

**Comment by YZZ321** [comment]
按这个试下，我成功了，https://github.com/tuanzi0701/notion_cn

**Comment by Summer754** [comment]
> 按这个试下，我成功了，https://github.com/tuanzi0701/notion_cn

亲测可用，替换文件后打开会一直转圈，推出后重新进即可正常进入。

**Comment by Reamd7** [comment]
下载 app.mac.zip，解压得到 app 文件夹，删除app.asar 把 app 文件夹拖进去

![20231127180252_rec_](https://github.com/Reamd7/notion-zh_CN/assets/22834225/b7f08d3f-f87d-414d-a630-a3ca7d592a8b)

**Comment by Reamd7** [comment]
已经修复了因为切换语言导致的都变成英文的问题，请下载最新版本的app.zip
