### ISSUE TITLE
3.0版的汉化，Win 使用后没有效果。

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [Reamd7/notion-zh_CN#136]
全新安装 Notion ，Notion数据文件夹、app.asa也都删除了。
按说明自己改，或者 app.win.zip 文件解压后替换，都没用。
请问是什么原因？

**Comment by Reamd7** [comment]
> 全新安装 Notion ，Notion数据文件夹、app.asa也都删除了。 按说明自己改，或者 app.win.zip 文件解压后替换，都没用。 请问是什么原因？

方便录屏吗？只需要删app.asar 把解压后的文件夹app放到同级目录下就可以了啊

**Comment by awayfun** [comment]
打不开notion。一直转圈圈。

**Comment by wy16W2pIilK1xgqN** [comment]
> > 全新安装 Notion ，Notion数据文件夹、app.asa也都删除了。 按说明自己改，或者 app.win.zip 文件解压后替换，都没用。 请问是什么原因？
> 
> 方便录屏吗？只需要删app.asar 把解压后的文件夹app放到同级目录下就可以了啊

没必要录屏。
我大致说一下系统环境.
Win11  22H2
文件路径
C:\Users\用户名\AppData\Local\Programs\Notion\resources\app\.webpack\main\index.js
index.js的哈希值
MD5: AB62F5DC1B2601EBDA911F5B82660B72
SHA1: 013FB11F4F062F1B2B8218CC82E6FAF60BA27B1D
SHA256: A5BF60347404C566CAEEE39A73231156124A9581CD9534F32EFD2945CC85F46B
CRC32: 379CE984

**Comment by awayfun** [comment]
搞定了，是因为我没升级到3.0，网络不好，升级完就好了。

**Comment by Reamd7** [comment]
我没办法判断，直接用 release 的app文件就好了吧

**Comment by wy16W2pIilK1xgqN** [comment]
问题已经解决！！
在Notion 来回切换几次语言就可以了。
过程中可能出现长时间显示转圈，一定要等待Notion 自己完成语言切换。

谢谢 @Reamd7  🌼
