### ISSUE TITLE
解压丢进去文件报错，windows

### ISSUE THREAD

**Issue by Junjie06** [Reamd7/notion-zh_CN#138]
![image](https://github.com/Reamd7/notion-zh_CN/assets/96861486/cc95aac3-1327-43cb-870d-1bf5cced7160)

名称改了，蒋解压出来的文件丢进去， 启动报错了这个

**Comment by Reamd7** [comment]
请下载最新版本 https://www.notion.so/desktop/windows/download 我本地的同级目录有 trayIcon.ico 这个文件的
