### ISSUE TITLE
3.0.0 notion 客户端 MAC-汉化失效（已解决/另辟蹊径）

### ISSUE THREAD

**Issue by SayNo233** [Reamd7/notion-zh_CN#139]
https://github.com/Reamd7/notion-zh_CN/releases/tag/3.0.0

根据这个操作更新我的Notion文件，但是重启后并没有效果。

**Comment by SayNo233** [comment]
我只操作了这些内容，删除app.asar,复制解压后的app文件 到原本位置。


是否需要反编译成asar文件之类？或者去app文件里面配置zh？
<img width="920" alt="image" src="https://github.com/Reamd7/notion-zh_CN/assets/59193922/8c58dfa2-d69f-475d-88c7-319ac8e0d874">
<img width="920" alt="image" src="https://github.com/Reamd7/notion-zh_CN/assets/59193922/6f2c5b95-84f8-464c-8c7e-d7bb750ee4fa">

**Comment by Reamd7** [comment]
不需要反编译除非你希望自己做一个编译后的包。你是不是没有完全退出notion（状态栏）

**Comment by wang-zhengxin** [comment]
我也是3.0.0 mac版本  替换后无效

**Comment by yangshyu** [comment]
无效，老铁

**Comment by Reamd7** [comment]
如果希望解决问题的同学可以贴录屏。我确定我本地mac的notion是汉化成功的。

**Comment by happykkAi** [comment]
如果汉化失败，可以试着把这个app.asar 放到文件夹里 https://github.com/Reamd7/notion-zh_CN/releases/tag/2.4.20-handmade  ，

**Comment by Moth-X** [comment]
> 如果汉化失败，可以试着把这个app.asar 放到文件夹里 https://github.com/Reamd7/notion-zh_CN/releases/tag/2.4.20-handmade ，

感谢你，Win11一开始按教程操作汉化无效，将这个app.asar替换原文件后汉化成功了。

**Comment by Joggiwang** [comment]
> https://github.com/Reamd7/notion-zh_CN/releases/tag/3.0.0
> 
> 根据这个操作更新我的Notion文件，但是重启后并没有效果。
你可以在设置里语言和地区切换一下日语或者其他语言，然后重启就可以了

**Comment by SayNo233** [comment]
https://github.com/tuanzi0701/notion_cn
目前根据这个操作，已实现汉化，等待这边的解决方案。
根据这个操作的时候，第一次会转圈圈，然后重启app 登录就好。（重复几次）
<img width="1278" alt="image" src="https://github.com/Reamd7/notion-zh_CN/assets/59193922/cadd1946-102e-4756-b838-551535c3255e">

**Comment by Reamd7** [comment]
> https://github.com/tuanzi0701/notion_cn 目前根据这个操作，已实现汉化，等待这边的解决方案。 根据这个操作的时候，第一次会转圈圈，然后重启app 登录就好。（重复几次） <img alt="image" width="1278" src="https://private-user-images.githubusercontent.com/59193922/289419977-cadd1946-102e-4756-b838-551535c3255e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNTk0NDQsIm5iZiI6MTcwMjM1OTE0NCwicGF0aCI6Ii81OTE5MzkyMi8yODk0MTk5NzctY2FkZDE5NDYtMTAyZS00NzU2LWI4MzgtNTUxNTM1YzMyNTVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA1MzIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4OWY1MmFjZDllMjY2NGVlMWNlY2VjOTVmNzBjNmVmMGVkYmQ4NTkyODFiM2ZmYTYxMmM5MzU4NDkxZDI1ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0q7b1lEWNJbb-gU199oKaNh0FSw9n05ejB0b_e-iBAQ">

这是用了旧版本的notion套在3.0的壳子上。你的问题，我无法复现，非要开箱即用只能提供单独安装包了

**Comment by githubcatheaven** [comment]
你去官网下啊，我昨天下的dmg，universal版本，还是不能用汉化

**Comment by Reamd7** [comment]
3.1.0 客户端已更新


> 你去官网下啊，我昨天下的dmg，universal版本，还是不能用汉化

**Comment by NaiveMMM** [comment]
mac下了3.1的改了文件后一直在转圈圈

**Comment by colorfulandcjy0806** [comment]
> mac下了3.1的改了文件后一直在转圈圈
https://github.com/Reamd7/notion-zh_CN/releases/tag/2.4.20-handmade，我刚刚也遇到了这个问题，但是我通过下载这里的app.asar，并加入到Resources文件夹下面，就成功了！

**Comment by colorfulandcjy0806** [comment]
> mac下了3.1的改了文件后一直在转圈圈

[https://github.com/Reamd7/notion-zh_CN/releases/tag/2.4.20-handmade](https://github.com/Reamd7/notion-zh_CN/releases/tag/2.4.20-handmade)，我刚刚也遇到了这个问题，但是我通过下载这里的app.asar，并加入到Resources文件夹下面，就成功了！

**Comment by Reamd7** [comment]
3.1 版本的 app.mac.zip 已经修复
