### ISSUE TITLE
「吐槽」notion官方是和中文化有仇么？

### ISSUE THREAD

**Issue by aaazz47** [Reamd7/notion-zh_CN#140]
抱歉发了这么一个和项目本身没有直接关系的 Issue 如果觉得不合适麻烦删除之类的。但是不吐不快

我用notion时间不长，对于英语不好的我来说，这个汉化项目正是我的救星。但是短短半年的使用时间我却有种官方对于中文化的“恶意”
几乎每次都是更新后和汉化补丁不兼容。尤其升级 3.0 这次，我觉得这个项目差不多是从头来过了一遍，好不容易有了 APP 文件这个看起了类似“解包”的方式成功再次汉化了，这次更新又是需要重新下载。

是一直以来都这样么？

**Comment by Reamd7** [comment]
更新软件从来都是要重新下载的。

**Comment by Reamd7** [comment]
之后可能我会做一个轻量级的 Notion unoffical 客户端

**Comment by hsiangron** [comment]
如果你觉得一直汉化麻烦的话，为什么不考虑学一点英语呢，看懂软件的要求应该不高

**Comment by Reamd7** [comment]
> 抱歉发了这么一个和项目本身没有直接关系的 Issue 如果觉得不合适麻烦删除之类的。但是不吐不快
> 
> 我用notion时间不长，对于英语不好的我来说，这个汉化项目正是我的救星。但是短短半年的使用时间我却有种官方对于中文化的“恶意” 几乎每次都是更新后和汉化补丁不兼容。尤其升级 3.0 这次，我觉得这个项目差不多是从头来过了一遍，好不容易有了 APP 文件这个看起了类似“解包”的方式成功再次汉化了，这次更新又是需要重新下载。
> 
> 是一直以来都这样么？

如果你不想更新重新下载可以删除 update.yml 禁止自动更新
