### ISSUE TITLE
Mac电脑 notion 3.1.1汉化失败

### ISSUE THREAD

**Issue by xianfeizhu** [Reamd7/notion-zh_CN#152]
按照博主的步骤下载解压好app这个文件然后拖进source里并删除app.asar，重启软件并没有汉化成功，有人也遇到这种问题吗

**Comment by jennyQinJN** [comment]
在notion版本更新为3.1.1 遇到了同样的问题，之前下载版本为3.1.0，resource中替换文件后，显示“正在下载更新”，更新后替换汉化失败。我看了下之前下载的文件，把package.json中的“version”:"3.1.0",字段改成“version”:"3.1.1"，再重启软件就汉化成功了。暂时可行。

**Comment by xianfeizhu** [comment]
> 在notion版本更新为3.1.1 遇到了同样的问题，之前下载版本为3.1.0，resource中替换文件后，显示“正在下载更新”，更新后替换汉化失败。我看了下之前下载的文件，把package.json中的“version”:"3.1.0",字段改成“version”:"3.1.1"，再重启软件就汉化成功了。暂时可行。

还是不行，请问你的处理方法是windows上还是mac上？由于我的是mac，按照你说的方法试了下，还是没有汉化成功，此外，加入修改后内容的app文件夹到resource后重启notion，本应该有的app.asar文件没有了，是不是这其中出错了😭😭

**Comment by phoenix-cn** [comment]
> > 在notion版本更新为3.1.1 遇到了同样的问题，之前下载版本为3.1.0，resource中替换文件后，显示“正在下载更新”，更新后替换汉化失败。我看了下之前下载的文件，把package.json中的“version”:"3.1.0",字段改成“version”:"3.1.1"，再重启软件就汉化成功了。暂时可行。
> 
> 还是不行，请问你的处理方法是windows上还是mac上？由于我的是mac，按照你说的方法试了下，还是没有汉化成功，此外，加入修改后内容的app文件夹到resource后重启notion，本应该有的app.asar文件没有了，是不是这其中出错了😭😭

我是mac，用楼上的办法可行

**Comment by xianfeizhu** [comment]
> > > 在notion版本更新为3.1.1 遇到了同样的问题，之前下载版本为3.1.0，resource中替换文件后，显示“正在下载更新”，更新后替换汉化失败。我看了下之前下载的文件，把package.json中的“version”:"3.1.0",字段改成“version”:"3.1.1"，再重启软件就汉化成功了。暂时可行。
> > 
> > 
> > 还是不行，请问你的处理方法是windows上还是mac上？由于我的是mac，按照你说的方法试了下，还是没有汉化成功，此外，加入修改后内容的app文件夹到resource后重启notion，本应该有的app.asar文件没有了，是不是这其中出错了😭😭
> 
> 我是mac，用楼上的办法可行

我的resource是这样的，能否给我看看你的resource包里有啥文件夹呢？
![WeChat896fc3ace75ad23cc49bfea09781260b](https://github.com/Reamd7/notion-zh_CN/assets/73736300/1393d429-d5b6-4789-894c-adecdaf9929e)

**Comment by phoenix-cn** [comment]
是改下载的app文件夹里的package.json

**Comment by Stanshen123** [comment]
> 是改下载的app文件夹里的package.json

请问用直接拉下载的app这个文件全删除app.asar这个方法还能改简中或繁中吗？装上去都是简中，不知道怎么改繁中

**Comment by louiejordan** [comment]
> 在notion版本更新为3.1.1 遇到了同样的问题，之前下载版本为3.1.0，resource中替换文件后，显示“正在下载更新”，更新后替换汉化失败。我看了下之前下载的文件，把package.json中的“version”:"3.1.0",字段改成“version”:"3.1.1"，再重启软件就汉化成功了。暂时可行。

Windows试了，这方法可行

**Comment by ada-Kim123** [comment]
windows，用了楼上方法，好用

**Comment by xianfeizhu** [comment]
> 是改下载的app文件夹里的package.json
是，我也改了的，但是好像还是不行，只有我受伤的世界达成了
![WechatIMG1812](https://github.com/Reamd7/notion-zh_CN/assets/73736300/29dcb55b-1949-4738-a3e8-adb16c9a3a21)

**Comment by kyc20010501** [comment]
macOS 14.3，Notion 3.1.1亲测可用

**Comment by luck-xj** [comment]
> 在notion版本更新为3.1.1 遇到了同样的问题，之前下载版本为3.1.0，resource中替换文件后，显示“正在下载更新”，更新后替换汉化失败。我看了下之前下载的文件，把package.json中的“version”:"3.1.0",字段改成“version”:"3.1.1"，再重启软件就汉化成功了。暂时可行。

有效，但是要搭配这个一起食用https://github.com/Reamd7/notion-zh_CN/issues/84

**Comment by xianfeizhu** [comment]
> > 在notion版本更新为3.1.1 遇到了同样的问题，之前下载版本为3.1.0，resource中替换文件后，显示“正在下载更新”，更新后替换汉化失败。我看了下之前下载的文件，把package.json中的“version”:"3.1.0",字段改成“version”:"3.1.1"，再重启软件就汉化成功了。暂时可行。
> 
> 有效，但是要搭配这个一起食用#84

强啊，大佬，正如你所说的，切换一下任意语言就可以实现汉化了。不过还有个问题，汉化后的notion，你们的左上角的菜单栏能汉化吗？我的好像不行。
<img width="525" alt="image" src="https://github.com/Reamd7/notion-zh_CN/assets/73736300/c3305df2-835b-40b3-a5e5-a78060a51661">

**Comment by luck-xj** [comment]
> > > 在notion版本更新为3.1.1 遇到了同样的问题，之前下载版本为3.1.0，resource中替换文件后，显示“正在下载更新”，更新后替换汉化失败。我看了下之前下载的文件，把package.json中的“version”:"3.1.0",字段改成“version”:"3.1.1"，再重启软件就汉化成功了。暂时可行。
> > 
> > 
> > 有效，但是要搭配这个一起食用#84
> 
> 强啊，大佬，正如你所说的，切换一下任意语言就可以实现汉化了。不过还有个问题，汉化后的notion，你们的左上角的菜单栏能汉化吗？我的好像不行。 <img alt="image" width="525" src="https://private-user-images.githubusercontent.com/73736300/298876209-c3305df2-835b-40b3-a5e5-a78060a51661.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDU5ODgsIm5iZiI6MTcwNjAwNTY4OCwicGF0aCI6Ii83MzczNjMwMC8yOTg4NzYyMDktYzMzMDVkZjItODM1Yi00MGIzLWE1ZTUtYTc4MDYwYTUxNjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEwMjgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMzBhMzc0NGRkOWNhNTg3NGU5NGZkZTAwYzg1Yzk2NWNlMzQyNzNhNTViYTczZWMwNzg1ZmUwMTJmNWMxMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GIxiOceydEHEipghY_a15fiFVEEN1-ekNSg9ce80WNE">

我的也不行，应该菜单是没做汉化的

**Comment by KittyYanpy** [comment]
> macOS 14.3，Notion 3.1.1亲测可用

请问是哪个方法管用了的？resource中替换文件之后切换语言还是别的方法？

**Comment by Limumuloveworld** [comment]
> 在notion版本更新为3.1.1 遇到了同样的问题，之前下载版本为3.1.0，resource中替换文件后，显示“正在下载更新”，更新后替换汉化失败。我看了下之前下载的文件，把package.json中的“version”:"3.1.0",字段改成“version”:"3.1.1"，再重启软件就汉化成功了。暂时可行。

大佬现在3.4版本怎么汉化哦，我用博主的方法后notion都打不开了，这是为啥啊🤕
