### ISSUE TITLE
使用脚本后，无法正常显示 12 小时制时间

### ISSUE THREAD

**Issue by l782993610** [Reamd7/notion-zh_CN#16]
<img width="512" alt="截屏2021-10-05 10 01 16" src="https://user-images.githubusercontent.com/59809602/135948539-4c55f054-e356-400d-89c7-1f64ad862aa6.png">

**Comment by l782993610** [comment]
推测日期、时间显示与语言相关，星期、日期显示是正确的，只有 12 小时制时间不对

**Comment by Reamd7** [comment]
这是官方的锅：https://www.notion.so/index-zh-CN-c1afa1ed63dff2000feb.html 关闭油猴脚本，进入最新版本的这个中文首页，然后回到我的内容

**Comment by Reamd7** [comment]
其实是notion使用的国际化时间库的问题（虽然我不知道为什么业界到现在都不改）

**Comment by S-Kee** [comment]
> 这是官方的锅：https://www.notion.so/index-zh-CN-c1afa1ed63dff2000feb.html 关闭油猴脚本，进入最新版本的这个中文首页，然后回到我的内容

请问这个从哪里可以看到最新的链接啊。

**Comment by Reamd7** [comment]
https://github.com/Reamd7/notion-zh_CN/blob/main/util/syncAssest.js
```
const assest = await axios.default.post(
    "https://www.notion.so/api/v3/getAssetsJsonV2",
    {
      hash: "",
    },
    {
      timeout: 10000000
    }
  ).catch(e => {
    console.log(e)
  });
```

> > 这是官方的锅：https://www.notion.so/index-zh-CN-c1afa1ed63dff2000feb.html 关闭油猴脚本，进入最新版本的这个中文首页，然后回到我的内容
> 
> 请问这个从哪里可以看到最新的链接啊。

**Comment by Reamd7** [comment]
> > 这是官方的锅：https://www.notion.so/index-zh-CN-c1afa1ed63dff2000feb.html 关闭油猴脚本，进入最新版本的这个中文首页，然后回到我的内容
> 
> 请问这个从哪里可以看到最新的链接啊。

或者在本地客户端的资源缓存看到

**Comment by Reamd7** [comment]
> > https://github.com/Reamd7/notion-zh_CN/blob/main/util/syncAssest.js
> > ```
> > const assest = await axios.default.post(
> >     "https://www.notion.so/api/v3/getAssetsJsonV2",
> >     {
> >       hash: "",
> >     },
> >     {
> >       timeout: 10000000
> >     }
> >   ).catch(e => {
> >     console.log(e)
> >   });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > > 这是官方的锅：https://www.notion.so/index-zh-CN-c1afa1ed63dff2000feb.html 关闭油猴脚本，进入最新版本的这个中文首页，然后回到我的内容
> > > 
> > > 
> > > 请问这个从哪里可以看到最新的链接啊。
> 
> 可否请教一下，我用node在本地运行这个js，什么都没输出，请问需要怎么处理吗？

如果你理解就知道只不过是一个post请求到这个接口。。。

**Comment by Reamd7** [comment]
> 推测日期、时间显示与语言相关，星期、日期显示是正确的，只有 12 小时制时间不对

2.3.7 版本：原来moment.js 有挂载在window，所以借助这个特性修改中文时间格式（支持24小时）
