### ISSUE TITLE
输入中文时，输入法焦点总是在左上角

### ISSUE THREAD

**Issue by astar99** [Reamd7/notion-zh_CN#17]
![image](https://user-images.githubusercontent.com/53571272/136333001-f1a12fc3-322d-41f4-a843-c890cb2cd6c5.png)
已经按照说明，手动替换了js文件，但是还是不行，已经把notion设置里面的中文beta改为了English，或者说，notion桌面端输入中文一直都有这样的问题吗？

**Comment by cooky-dance** [comment]
没遇到你这个情况，正常输入

**Comment by Reamd7** [comment]
更新了几个版本之后没有遇见notion本体的这个问题了

**Comment by push314** [comment]
完全一样的问题，在新打开notion的时候有大概2成的概率出现，大概使用一会就会恢复。同样是win环境。

**Comment by litelte** [comment]
1.我也遇到了同样的问题，更换了几个版本的notion-zh_CN都不行。
2.最后发现：在使用notion桌面端的时候，开始菜单会失焦。
3.不过后来在开始菜单栏里输入了一个字后，再切回notion的桌面端，中文输入法又回到了正常的位置。
4.不知道大家的可以这样吗，我用的是Windows11专业版，处理器是AMD的3500X

**Comment by Heartbleed98** [comment]
都多久了，这个bug还没修复，我都服了

**Comment by 0zhiyang** [comment]
我也遇到了同样的问题，桌面端的notion，Windows11；
刚想寻找解决办法看到了题主这个问题，然后自己再打开notion时输入法又恢复了正常
![image](https://user-images.githubusercontent.com/117663065/217494571-c33ba841-aaa2-4646-8de9-b515e041e83a.png)

**Comment by hyyxiaoluo** [comment]
> 我也遇到了同样的问题，桌面端的notion，Windows11; 刚想寻找解决办法看到了题主这个问题，然后自己再打开notion时输入法又恢复了正常 ![图像](https://user-images.githubusercontent.com/117663065/217494571-c33ba841-aaa2-4646-8de9-b515e041e83a.png)
你好，你的win11的输入法看起来好圆润，很好看，包括输入法的主题配色，具体则呢么实现的呢，这应该不是微软雅黑字体吧，很感兴趣，希望得到回复！！

**Comment by 0zhiyang** [comment]
> 

![image](https://user-images.githubusercontent.com/117663065/224548332-1394f22d-c6cd-4c8b-8aa1-564301207873.png)
你看看是不是开了兼容性。
是微软雅黑，不过也可以自己改字体。个性化>文本输入

**Comment by 0zhiyang** [comment]
> > 你好，你的win11的输入法看起来好圆润，很好看，包括输入法的主题配色，具体则呢么实现的呢，这应该不是微软雅黑字体吧，很感兴趣，希望得到回复！！

![image](https://user-images.githubusercontent.com/117663065/224552189-c385ba1a-69cc-4afa-9672-2b5295342b2d.png)
看看是不是打开了兼容性吧。
我用的字体是微软雅黑没改，主题和字体可以在 个性化>文本输入 里改

**Comment by lucafei** [comment]
同样的问题，希望官方快点解决这个bug

**Comment by hulichao** [comment]
输入法这个问题，正如前面楼上说的，刚打卡notion刚开始有一定概率会出现，但是你切换到别的应用，再打会字，回去就好了

**Comment by xpywhq** [comment]
> 1.我也遇到了同样的问题，更换了几个版本的notion-zh_CN都不行。 2.最后发现：在使用notion桌面端的时候，开始菜单会失焦。 3.不过后来在开始菜单栏里输入了一个字后，再切回notion的桌面端，中文输入法又回到了正常的位置。 4.不知道大家的可以这样吗，我用的是Windows11专业版，处理器是AMD的3500X

感谢，这个方法很好用。

**Comment by icarsone** [comment]
> 1.我也遇到了同样的问题，更换了几个版本的notion-zh_CN都不行。 2.最后发现：在使用notion桌面端的时候，开始菜单会失焦。 3.不过后来在开始菜单栏里输入了一个字后，再切回notion的桌面端，中文输入法又回到了正常的位置。 4.不知道大家的可以这样吗，我用的是Windows11专业版，处理器是AMD的3500X

确实可以欸=呜呜呜呜

**Comment by redphosphorus7562** [comment]
> 1.我也遇到了同样的问题，更换了几个版本的notion-zh_CN都不行。 2.最后发现：在使用notion桌面端的时候，开始菜单会失焦。 3.不过后来在开始菜单栏里输入了一个字后，再切回notion的桌面端，中文输入法又回到了正常的位置。 4.不知道大家的可以这样吗，我用的是Windows11专业版，处理器是AMD的3500X

好用感谢

**Comment by chareice** [comment]
> 1.我也遇到了同样的问题，更换了几个版本的notion-zh_CN都不行。 2.最后发现：在使用notion桌面端的时候，开始菜单会失焦。 3.不过后来在开始菜单栏里输入了一个字后，再切回notion的桌面端，中文输入法又回到了正常的位置。 4.不知道大家的可以这样吗，我用的是Windows11专业版，处理器是AMD的3500X

都是什么神奇骚操作，搁这卡BUG呢

**Comment by saltyfishyjk** [comment]
> 1.我也遇到了同样的问题，更换了几个版本的notion-zh_CN都不行。 2.最后发现：在使用notion桌面端的时候，开始菜单会失焦。 3.不过后来在开始菜单栏里输入了一个字后，再切回notion的桌面端，中文输入法又回到了正常的位置。 4.不知道大家的可以这样吗，我用的是Windows11专业版，处理器是AMD的3500X

好用好用，感谢，没想到快2024年了这个bug还没修复😂

**Comment by zhangchuheng123** [comment]
在网页端：MacOS + Safari + 搜狗输入法 也遇到同样的问题，输入中文时焦点会跑到文档最前端。希望能尽快修复

**Comment by Kiyoaki2001** [comment]
> 1.我也遇到了同样的问题，更换了几个版本的notion-zh_CN都不行。 2.最后发现：在使用notion桌面端的时候，开始菜单会失焦。 3.不过后来在开始菜单栏里输入了一个字后，再切回notion的桌面端，中文输入法又回到了正常的位置。 4.不知道大家的可以这样吗，我用的是Windows11专业版，处理器是AMD的3500X

我去还真是，感谢

**Comment by mh-24** [comment]
同样，这个问题到现在还会出现，每次重启后打开notion第一次输入就会有这种情况，需要打开菜单后输入一次才可以。
