### ISSUE TITLE
API那里被翻译成了整合，官方用的就是API

### ISSUE THREAD

**Issue by S-Kee** [Reamd7/notion-zh_CN#2]
API那里被翻译成了整合，官方用的就是API

**Comment by Reamd7** [comment]
英文对应的是 integration 吧？翻译成集成？

**Comment by S-Kee** [comment]
API大家好像一般都不翻译，大家说也就是说API

**Comment by Reamd7** [comment]
中文版官方没有用API这样的翻译。

**Comment by S-Kee** [comment]
https://www.notion.so/index-zh-CN-6a31bd9c1dbf896f2bc4.html
我从这个网址进去，看到的。
![image](https://user-images.githubusercontent.com/21167731/129898724-1c0956b2-66c0-45d6-a595-e07aa09fbdec.png)

**Comment by Reamd7** [comment]
你没有发现图标都不同嘛（功能都不同），你这个链接太旧了，最新的多语言版本{
  'en-US': '/index-en-US-59c282513cb4d614f561.html',
  'es-ES': '/index-es-ES-557827a477bcd4bafa4d.html',
  'es-LA': '/index-es-LA-7ed1161de2b2cb9d6072.html',
  'fr-FR': '/index-fr-FR-5eea929619fe6ed1861b.html',
  'ja-JP': '/index-ja-JP-f2d7cb800ac87081ccf3.html',
  'ko-KR': '/index-ko-KR-23f209683880ceec005d.html',
  'pt-BR': '/index-pt-BR-9877a705b918169c2ce5.html',
  'zh-CN': '/index-zh-CN-2660d152fe885f55b9c4.html',
  'zh-TW': '/index-zh-TW-aac3fcd8307a4a512334.html'
}
https://www.notion.so/index-zh-CN-2660d152fe885f55b9c4.html

**Comment by S-Kee** [comment]
谢谢了。那就现在这样挺好的，我自己在本地改成了接口。
