### ISSUE TITLE
希望能让用户自定义 “快捷键输入”

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [Reamd7/notion-zh_CN#21]
发现官方的新功能“表”没有对应 ‘拼音快捷输入“，想想每次这些小更新都要开发者更改文件并不是个好主意。

能否做一个通用的配置方法出来，让用自己设定。

这样既能够减少开发者的重复劳动，又方便用户个性化。

**Comment by Reamd7** [comment]
加班中

**Comment by Reamd7** [comment]
不知道怎么交互，我告诉原理就是定制fuzzySearchWord的国际化字段。

**Comment by wy16W2pIilK1xgqN** [comment]
> 不知道怎么交互，我告诉原理就是定制fuzzySearchWord的国际化字段。

谢谢指点，我自己去尝试一下。
 😊

**Comment by Reamd7** [comment]
> > 不知道怎么交互，我告诉原理就是定制fuzzySearchWord的国际化字段。
> 
> 谢谢指点，我自己去尝试一下。 😊

其实代码中有一个fuzzySearchWord 的 js，我是人工单独将相关词条提取出来进行独立处理的，这个版本还没有时间去做这样的工作

**Comment by wy16W2pIilK1xgqN** [comment]
> 

多谢告知。
期待这个功能。
😁
