### ISSUE TITLE
汉化版的notion无法登陆谷歌账号

### ISSUE THREAD

**Issue by FloatingDream528** [Reamd7/notion-zh_CN#23]
作者大大您好，我发现用原版的notion可以正常登录谷歌账号，换成汉化版的就不行，有什么解决办法吗？

**Comment by hululu1068** [comment]
> 

先登录再汉化。。。。有时候转换下思路，问题就不是问题

**Comment by Reamd7** [comment]
> 作者大大您好，我发现用原版的notion可以正常登录谷歌账号，换成汉化版的就不行，有什么解决办法吗？

我试用了一下，我这边的情况是如果开启了油猴脚本下登录谷歌账号，初次登陆汉化会不生效，建议刷新一下
