### ISSUE TITLE
mac客户端修改无效

### ISSUE THREAD

**Issue by shelken** [Reamd7/notion-zh_CN#24]
版本为最新2.0.18；按照教程放入js文件。修改preload；重启，没有效果；

**Comment by Reamd7** [comment]
我自己就在用

**Comment by shelken** [comment]
> 我自己就在用

是不是m1的原因

**Comment by Reamd7** [comment]
我就是m1，是不是你js语法贴错了

**Comment by ssq001** [comment]
我是2.0.19版本的 也没有效果，很奇怪

**Comment by ChowRex** [comment]
> # 我是2.0.19版本的 也没有效果，很奇怪
> 设置里语言改成韩文生效了

实测MBP 2021 M1 Pro 系统版本 12.1
修改一次语言, 然后再改回英文可以生效, 猜测是notion并不是每次都读取语言配置吧? 可能只有切换的时候才会重新执行`prelpad.js`这个文件

**Comment by KatWei** [comment]
> > # 我是2.0.19版本的 也没有效果，很奇怪
> > 设置里语言改成韩文生效了
> 
> 实测MBP 2021 M1 Pro 系统版本 12.1 修改一次语言, 然后再改回英文可以生效, 猜测是notion并不是每次都读取语言配置吧? 可能只有切换的时候才会重新执行`prelpad.js`这个文件 @Reamd7 麻烦大佬修改一下Readme吧, 这个issue就可以关闭了😉

MacOS 系统版本 11.3，需要在设置中切换语言生效

**Comment by Reamd7** [comment]
我是MBP 2021 M1 Pro 12.0.1 MacOS，我看官网还是只有 2.0.18 版本的 M1 客户端。
