### ISSUE TITLE
請求授權翻譯權限

### ISSUE THREAD

**Issue by Edemilorhea** [Reamd7/notion-zh_CN#26]
想請問貢獻者、作者群們，是否願意讓我把語言翻譯成繁體中文，並重新優化字眼。

推廣給公司使用Notion買了團隊版，但同事們的英文實在是不太行，想請問作者是否願意讓我重新編修內容，進行使用。

因為部分用語在台灣是不太通順的，所以有了想自己動手的念頭，想在此先向作者們告知。

**Comment by Reamd7** [comment]
周五，我整理一下繁体中文的环境与分支。然后你再fork进行翻译吧

**Comment by Reamd7** [comment]
因为官方也有繁体中文的基础语言字段，所以先处理一下再建立新分支给你fork

**Comment by pipepuppy** [comment]
你看你都去年了，不知道现在解决了没。我搞了个繁体版的办法，不知道合适不
https://pipepuppy.com/archives/230/

**Comment by Edemilorhea** [comment]
> 

啊，非常感謝您的協作，我後來其實有在內部做一個給同仁使用，但是我後來太忙了，也忘了要PR上來。

**Comment by Reamd7** [comment]
https://greasyfork.org/zh-CN/scripts/463049-notion-zh-tw-notion%E7%9A%84%E6%B1%89%E5%8C%96%E8%84%9A%E6%9C%AC

以及最新的Notion-zh_TW.js 脚本已经更新

都是使用官方的语料 看看是不是符合繁体中文的用词，体验之后方便的话继续在此进行反馈？如果用词确有问题我会尝试这个库您提供的这个仓库方案进行用词转换
