### ISSUE TITLE
桌面版-菜单栏的汉化

### ISSUE THREAD

**Issue by coralfox** [Reamd7/notion-zh_CN#3]
C:\Users\用户\AppData\Local\Programs\Notion\resources\app\main\systemMenu.js
文本是放在这个文件
简单汉化覆盖了下,,不清楚怎么使用加载方式调用

[systemMenu.txt](https://github.com/Reamd7/notion-zh_CN/files/7012640/systemMenu.txt)
![Snipaste_2021-08-19_15-49-35](https://user-images.githubusercontent.com/5997906/130029438-9e19fa62-34da-4f4e-bba5-8f5aaec07395.png)

**Comment by S-Kee** [comment]
![image](https://user-images.githubusercontent.com/21167731/130044614-4aacbeb9-c3ac-4fad-9158-22d3e157d5c7.png)
直接在这个文件加了一句，把菜单栏隐藏了，菜单栏又丑又没用。

**Comment by Reamd7** [comment]
官方最新客户端去掉了这个菜单栏了（普天同庆）
