### ISSUE TITLE
安卓12卡首页

### ISSUE THREAD

**Issue by tonynesss** [Reamd7/notion-zh_CN#30]
![Screenshot_2022-02-27-20-37-41-881_notion.zh_cn.png](https://user-images.githubusercontent.com/32998682/155882640-746456a5-e1ba-4f08-a4a7-f56760c12bb3.png)

**Comment by Reamd7** [comment]
抱歉。。我手上没有安卓机了。。

**Comment by flymdk** [comment]
我也是卡首页

**Comment by Joseph-Hamilton** [comment]
4.29th.2022 啊这，我直到几天前还一切正常，今天平板和手机也都卡首页了（均为华为）。

**Comment by CaesarWangRuiyuan** [comment]
挂梯子就好了

**Comment by CaesarWangRuiyuan** [comment]
> 我也是卡首页 

挂梯子

**Comment by CaesarWangRuiyuan** [comment]
> 4.29th.2022 啊这，我直到几天前还一切正常，今天平板和手机也都卡首页了（均为华为）。
> 
> 5.1 今天又试了一次，卡首页的问题，不清楚原因。

挂梯子

**Comment by wasaibi12345** [comment]
仍然会卡首页。。。

**Comment by decodegu** [comment]
无法使用Google登录，加载不出来

**Comment by wuzhee** [comment]
有梯子，卡登录页面，选择了Google登录之后，闪一下，登不进去

**Comment by Reamd7** [comment]
已经更新了最新的安卓了 https://github.com/Reamd7/notion-zh_CN/blob/main/apk/Notion_0.6.1122.beta(7122)_zh_cn.apk
