### ISSUE TITLE
安卓版汉化

### ISSUE THREAD

**Issue by ailinor** [Reamd7/notion-zh_CN#36]
辛苦了😊，
安卓版下载之后仍是英文界面

**Comment by ailinor** [comment]
> 辛苦了😊，
> 安卓版下载之后仍是英文界面

可以了，重启了一下，会白屏一会儿

**Comment by Reamd7** [comment]
已经更新了最新的安卓了 https://github.com/Reamd7/notion-zh_CN/blob/main/apk/Notion_0.6.1122.beta(7122)_zh_cn.apk
