### ISSUE TITLE
mac、windows都可以使用类似的命令当notion更新之后手动执行脚本

### ISSUE THREAD

**Issue by Romic77** [Reamd7/notion-zh_CN#43]
首先需要下载notion-zh_CN.js 到指定目录下，我是下载到/Users/chenqi/Downloads/notion-zh_CN.js此目录下。

1. 创建notion_cn.sh
2. chmod a+x notion_cn.sh
3. sh notion_cn.sh

`
cp /Users/chenqi/Downloads/notion-zh_CN.js /Applications/Notion.app/Contents/Resources/app/renderer/

echo  'require("./notion-zh_CN")' >>  /Applications/Notion.app/Contents/Resources/app/renderer/preload.js
`

**Comment by Romic77** [comment]
`
cp D:\迅雷下载\notion-zh_CN.js C:\Users\28038\AppData\Local\Programs\Notion\resources\app\renderer
cd C:\Users\28038\AppData\Local\Programs\Notion\resources\app\renderer
echo require("./notion-zh_CN") >> .\preload.js
`

**Comment by Romic77** [comment]
`
cp D:\迅雷下载\notion-zh_CN.js C:\Users\28038\AppData\Local\Programs\Notion\resources\app\renderer

cd C:\Users\28038\AppData\Local\Programs\Notion\resources\app\renderer

echo require("./notion-zh_CN") >> .\preload.js

`

**Comment by Romic77** [comment]
第一个是mac执行的shell脚本, 第二个是win执行的bat脚本 . 更新之后直接执行脚本即可.

**Comment by Reamd7** [comment]
不够通用。

**Comment by Romic77** [comment]
> 不够通用。

没办法获得notion更新的函数，不然更新之后自动触发脚本即可。
不同的操作系统没办法做通用脚本。除非做服务（笨重且没必要）

**Comment by Reamd7** [comment]
不同操作系统也是可以的。。unix提供shell，win提供ps/cmd。可以让用户一件注入之类的。。

**Comment by Reamd7** [comment]
> 

shell 版本的不太熟悉，随便写了一个在mac中运行
