### ISSUE TITLE
m1 pro notion2.1.1汉化失败

### ISSUE THREAD

**Issue by gaobinbin991314** [Reamd7/notion-zh_CN#44]
m1 pro 芯片 下载的notion 2.1.1，按照你这个教程汉化，但是重启以后还是英文

**Comment by gaobinbin991314** [comment]
在设置与成员中，将语言设置成为韩文，就汉化完毕！

**Comment by Reamd7** [comment]
> 在设置与成员中，将语言设置成为韩文，就汉化完毕！

这个机制我也搞不太懂。。有时候设置韩文才行有时候又不用
