### ISSUE TITLE
到底有没有官方中文版？

### ISSUE THREAD

**Issue by louiejordan** [Reamd7/notion-zh_CN#45]
既然词条数量和韩文差不多，那为什么不在语言beta列表里？感觉是个没头绪的东西

**Comment by Reamd7** [comment]
第一，模版没有官方中文化。
第二，帮助文档没有官方中文版。
第三，打入中国市场会有数据监管问题，这更涉及到企业经营的问题。
第四，中文语料是中文社区的爱好者和官方共同完成的。

所以我做了这个东西把官方隐藏的能力弄出来。
