### ISSUE TITLE
请问截图中的输入法是什么软件？

### ISSUE THREAD

**Issue by S-Kee** [Reamd7/notion-zh_CN#5]

**Comment by Reamd7** [comment]
微软拼音

**Comment by S-Kee** [comment]
微软拼音怎么可以这么好看？是win10下的吗？

**Comment by Reamd7** [comment]
win11

**Comment by Reamd7** [comment]
win10 也不差啊

**Comment by S-Kee** [comment]
![image](https://user-images.githubusercontent.com/21167731/131235075-6c032bb4-02bc-4e8e-a29b-1e262e5b13b1.png)
还是你的好看很多
