### ISSUE TITLE
没有汉化成功。 Mac 和网页端都失败了。 

### ISSUE THREAD

**Issue by xujin1184104394** [Reamd7/notion-zh_CN#50]

**Comment by jim3997516** [comment]
我的 也一样 10-17号开始

**Comment by tanmx** [comment]
同样的情况

**Comment by jim3997516** [comment]
切换到 韩文就可以了

**Comment by lucasmen9527** [comment]
10月27号亲测 我一开始也不行 下载汉化js后 切换韩语还是显示的韩语，我局把js删除了 又重新下载了一遍
版本 mac Version 2.1.4 (2.1.4)  再重启的时候 发现直接就是中文的了
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/64875226/197387222-80a0b164-0670-4229-9f40-f2bafa458330.png">

**Comment by fang2hou** [comment]
貌似现在 Notion 切换语言可以重建语言缓存, 客户端 `preload.js` 修改后需要手动改动一次语言.
