### ISSUE TITLE
貌似无法正常汉化了 

### ISSUE THREAD

**Issue by Mcurezhou** [Reamd7/notion-zh_CN#55]
notion-zh_CN.js无论是 mac还是网页端都下载进入 添加代码/更新油猴 都没有汉化成功 是我少了什么步骤么

<img width="1510" alt="截屏2022-11-21 10 57 04" src="https://user-images.githubusercontent.com/110305801/202954078-cbe18134-c4e0-4af1-a9b1-733abac0d472.png">

**Comment by zhangsubo** [comment]
我也是同样的问题

**Comment by zhangsubo** [comment]
> notion-zh_CN.js无论是 mac还是网页端都下载进入 添加代码/更新油猴 都没有汉化成功 是我少了什么步骤么
> 
> <img alt="截屏2022-11-21 10 57 04" width="1510" src="https://user-images.githubusercontent.com/110305801/202954078-cbe18134-c4e0-4af1-a9b1-733abac0d472.png">

你在这里更换一个语言试试，随便更换哪个都行。preferences里-语言和地区里，切换下语言，随便一个就行。然后 update 应该就可以了。
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/10377598/203893283-b81cf338-8538-4436-bee0-9eb5644ffce4.png">

**Comment by pasca520** [comment]
赞，原来还有这一步，我成功了。这个看能否放到说明里？
