### ISSUE TITLE
macbook M1芯片电脑 按照流程下载文件安装到包内重启，但是无法汉化？请教

### ISSUE THREAD

**Issue by Hdbxiansheng** [Reamd7/notion-zh_CN#68]

**Comment by hanyce** [comment]
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/37854396/220810106-cf3298d2-3a26-4971-8bc4-3c07673ae811.png">
同样的问题，我来帮忙贴个图

**Comment by Hdbxiansheng** [comment]
> 请问是怎么贴代码的?截图
我是打开对应的文件，把cn文件放进去文件夹后
在macbook电脑用--文本编辑方式打开preload.js文件，然后粘贴那段内容进去，然后关闭文件和软件。重新打开。

**Comment by jyking** [comment]
同样问题 mac m1 中文不生效
@Reamd7 

![WX20230223-115815@2x](https://user-images.githubusercontent.com/1525262/220818405-30df3c60-aa1b-430f-a155-ee2794cf5cfd.png)

**Comment by Reamd7** [comment]
手动在系统中切换一个语言为韩文试试...切换一下看看会不会生效,我也是m1没这个问题..

**Comment by hanyce** [comment]
@Reamd7 感谢，试了下可以了。切换下任意语言就自动换成中文了

**Comment by jyking** [comment]
@Reamd7  感谢，切换韩文。就能正常显示中文了。

**Comment by Reamd7** [comment]
可以切换回英文的

**Comment by Hdbxiansheng** [comment]
果然，切换一下韩文就解决了，舒服多了。太感谢，太感谢大家。
