### ISSUE TITLE
直接右键链接后，没有取消选中，反而处于拖拽的状态

### ISSUE THREAD

**Issue by FormatToday** [Reamd7/notion-zh_CN#7]
如动图所示，我只是右击了一个链接之后，左击了一次，但是后面一移动鼠标却发现处于拖拽状态了

![截图 20210908  Nv7jCuZR](https://user-images.githubusercontent.com/20515769/132438385-2f58933e-02ab-4faf-a456-9b5db31a6868.gif)

**Comment by Reamd7** [comment]
这跟汉化没关系啊
