### ISSUE TITLE
APK文件在安卓手机中打开无法登陆

### ISSUE THREAD

**Issue by LilQit7** [Reamd7/notion-zh_CN#72]
下载后在app内打开，不论是选择google账号登陆还是选择邮箱密码登陆都始终卡在登陆界面，这种应该怎么办？

**Comment by zx12331ac** [comment]
这是旧版的应该 需要点邮箱登录，新版也不知道怎么更新

**Comment by sakura-hua** [comment]
代理

**Comment by Reamd7** [comment]
已经更新了最新的安卓了 https://github.com/Reamd7/notion-zh_CN/blob/main/apk/Notion_0.6.1122.beta(7122)_zh_cn.apk
