### ISSUE TITLE
請問是否可以增加繁體中文？

### ISSUE THREAD

**Issue by Minidoracat** [Reamd7/notion-zh_CN#75]
https://github.com/BYVoid/OpenCC

其中的 s2twp.json 有自動用語轉換
希望可以考慮一下，謝謝

**Comment by Reamd7** [comment]
https://greasyfork.org/zh-CN/scripts/463049-notion-zh-tw-notion%E7%9A%84%E6%B1%89%E5%8C%96%E8%84%9A%E6%9C%AC

以及最新的Notion-zh_TW.js 脚本已经更新

都是使用官方的语料 看看是不是符合繁体中文的用词，体验之后方便的话继续在此进行反馈？如果用词确有问题我会尝试这个库您提供的这个仓库方案进行用词转换
