### ISSUE TITLE
安卓最新版部分没有翻译

### ISSUE THREAD

**Issue by bilibili2233a** [Reamd7/notion-zh_CN#80]
在左上角的头像、主界面和右上角的菜单三个点
完全没有翻译，搜索界面的搜索栏没有翻译。
![Collage_20230416_183938.jpg](https://user-images.githubusercontent.com/99982054/232300318-cd2b91e7-5819-4dd9-84ab-008571a44f19.jpg)
![Screenshot_20230416_184450_notion.zh_cn_edit_166098329886113.jpg](https://user-images.githubusercontent.com/99982054/232300912-2a3fbcb7-fba5-40ae-95c7-212e6c42ef3f.jpg)

**Comment by Reamd7** [comment]
是的，有一部分已经用原生写了，不是webview 所以不是使用汉化脚本的，我确认过这个效果
