### ISSUE TITLE
看看这个项目，哪个中文翻译的好？

### ISSUE THREAD

**Issue by chengaomin** [Reamd7/notion-zh_CN#9]
https://github.com/nancheung97/notion-zh_CN

**Comment by Reamd7** [comment]
网页端、PC、MAC端、cloudflare端都是我的方法更好，没有运行时压力。
IOS网页、安卓客户端注入，一半也是用了这个库的方法。

**Comment by chengaomin** [comment]
方法固然这个项目的好，我的意思是翻译那边好，可以借鉴

**Comment by Reamd7** [comment]
翻译的问题欢迎提issue，这个项目是基于中文小组的汉化成果基础上进行汉化的。
