### ISSUE TITLE
求助~切换语言只会显示英文

### ISSUE THREAD

**Issue by StephenBDR** [Reamd7/notion-zh_CN#95]
之前安装了大佬的汉化包，刚用了几天，今天突然变回了英文
重新安装，切换语言都没用，无论我切什么语言，都只有英文
已经搞了一天了，一直没法整好
帮帮忙，救救孩子吧！我快崩溃了！

**Comment by Apolsus** [comment]
今天失效了好像

**Comment by TTAlbert** [comment]
是的我也出现了同样的情况突然变回英文然后就变不回来了

**Comment by StephenBDR** [comment]
> 是的我也出现了同样的情况突然变回英文然后就变不回来了

话说，现在网页版还能汉化吗？

**Comment by instanceofs** [comment]
同样的问题，重装重启都无法切换成中文 MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)

**Comment by seszu** [comment]
估计要对中国的白嫖用户下手了

**Comment by Reamd7** [comment]
已修复

**Comment by StephenBDR** [comment]
> 已修复

感谢感谢！！英语苦手太需要了
