### ISSUE TITLE
桌面版无法汉化

### ISSUE THREAD

**Issue by TTAlbert** [Reamd7/notion-zh_CN#96]
重装重启重复步骤尝试都无法显示中文，好像无法识别中文语言包了，，呜呜呜~~~

**Comment by Cland-SKY** [comment]
网页版似乎也出现问题了

**Comment by ly5866** [comment]
Mac也凉了，无限英文改不过来，求大佬发挥神力吧！

**Comment by LPye151** [comment]
> 网页版似乎也出现问题了

是的，网页端也失效了已经

**Comment by neverup7** [comment]
等待大佬解决

**Comment by Ricardozm2020** [comment]
最新版无法汉化了呜呜呜呜呜

**Comment by ke-xi** [comment]
wwwwwwww大哥快修修

**Comment by Ai-Robots-world** [comment]
目前汉化是失效的了，耐心等待汉化文件的更新吧

**Comment by shiquda** [comment]
> > 网页版似乎也出现问题了
> 
> 是的，网页端也失效了已经

我稍微临时修了下，提交PR了
https://github.com/Reamd7/notion-zh_CN/pull/97

**Comment by Reamd7** [comment]
已修复
