### ISSUE TITLE
使用不了的，看最新的PR!

### ISSUE THREAD

**Issue by Jayzhuoct** [Reamd7/notion-zh_CN#99]

**Comment by Dear-XiaoBai** [comment]
’最新的PR‘是什么意思呢？

**Comment by Apolsus** [comment]
no no，这个 pr 没有修复客户端的问题，而且 `newScript` 的变量命名看起来很 dirty，难以理解。

**Comment by shiquda** [comment]
> no no，这个 pr 没有修复客户端的问题，而且 `newScript` 的变量命名看起来很 dirty，难以理解。

您好，我是 pr 的提交者， 这只是一个临时方案，对变量名的命名是一个临时命名，我对这个 notion 也不是很了解。至于客户端直接用那个脚本经过测试已经可以用了，最终可能还要等作者优化一下代码逻辑。感谢您的批评。

**Comment by StephenBDR** [comment]
> > no no，这个 pr 没有修复客户端的问题，而且 `newScript` 的变量命名看起来很 dirty，难以理解。
> 
> 您好，我是 pr 的提交者，说实话我正在学习 js 。 这个 pr 只是一个临时方案，对变量名的命名是一个临时命名，我对这个 notion 也不是很了解，所以代码里的其他结构不敢轻易修改，导致使用了一些奇怪的命名。 至于客户端直接用 pr 的那个脚本，经过测试，已经可以用了，最终可能还要等作者优化一下代码逻辑。 感谢您的批评。已经重新改了脚本。 [107c35a](https://github.com/Reamd7/notion-zh_CN/commit/107c35a9e35d316af681d7ad7d7a9b82e8e92a38)

大佬，我纯小白(┬＿┬)，求解释一下最新的PR是什么意思？应该怎么使用呢？很抱歉打扰您了

**Comment by shiquda** [comment]
> > > no no，这个 pr 没有修复客户端的问题，而且 `newScript` 的变量命名看起来很 dirty，难以理解。
> > 
> > 
> > 您好，我是 pr 的提交者，说实话我正在学习 js 。 这个 pr 只是一个临时方案，对变量名的命名是一个临时命名，我对这个 notion 也不是很了解，所以代码里的其他结构不敢轻易修改，导致使用了一些奇怪的命名。 至于客户端直接用 pr 的那个脚本，经过测试，已经可以用了，最终可能还要等作者优化一下代码逻辑。 感谢您的批评。已经重新改了脚本。 [107c35a](https://github.com/Reamd7/notion-zh_CN/commit/107c35a9e35d316af681d7ad7d7a9b82e8e92a38)
> 
> 大佬，我纯小白(┬＿┬)，求解释一下最新的PR是什么意思？应该怎么使用呢？很抱歉打扰您了

https://github.com/shiquda/notion-zh_CN/blob/main/notion-zh_CN.js

可以先复制到油猴里想临时使用，或者下载文件到app端替换掉旧的脚本使用

**Comment by StephenBDR** [comment]
> > > > 不不，这个问题没有修复客户端的问题，而且`newScript`指标命名看起来很肮脏，难以理解。
> > > 
> > > 
> > > 您好，我是 pr 的工作者，说实话我正在学习 js 。这个 pr 只是一个临时方案，对标志名的命名是一个临时命名，我对这个概念也不是很了解，所以代码里的其他结构不知道敢轻易修改，导致使用了一些奇怪的命名。相比客户端直接用pr的那种脚本，经过测试，已经可以用了，最终可能还需要等作者优化一下代码逻辑。感谢您的批评。已经重新改正了[107c35a](https://github.com/Reamd7/notion-zh_CN/commit/107c35a9e35d316af681d7ad7d7a9b82e8e92a38)脚本。[](https://github.com/Reamd7/notion-zh_CN/commit/107c35a9e35d316af681d7ad7d7a9b82e8e92a38)
> > 
> > 
> > 大佬，我纯小白(┬＿┬)，求解释一下最新的PR是什么意思？应该怎么用呢？很担心打扰您了
> 
> https://github.com/shiquda/notion-zh_CN/blob/main/notion-zh_CN.js
> 
> 可以先复制到油猴里先临时使用，或者下载文件到app端替换掉旧的脚本使用

好的好的，谢谢您，我试试看！

**Comment by kyc20010501** [comment]
> ’最新的PR‘是什么意思呢？

「最新的PR」指的是issues旁边的pull requests。如果是使用油猴脚本的话，可以去复制大佬的脚本https://github.com/shiquda/notion-zh_CN/blob/main/notion-zh_CN.js，替代原有的即可

**Comment by yunzhongci** [comment]
感谢，已经用上了

**Comment by Dear-XiaoBai** [comment]
> > ’最新的PR‘是什么意思呢？
> 
> 「最新的PR」指的是issues旁边的pull requests。如果是使用油猴脚本的话，可以去复制大佬的脚本https://github.com/shiquda/notion-zh_CN/blob/main/notion-zh_CN.js 替代原有的即可

感谢，已经搞定了

**Comment by Reamd7** [comment]
已修复
